[book]
authors = ["SLMT"]
language = "zh-TW"
multilingual = false
src = "src"
title = "股癌美股夜貓仔精華"

[output.html]
no-section-label = true
git-repository-url = "https://test"

[output.html.fold]
enable = false
